/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package registerpanel;

import insert.methods;
import registerpanel.Constructors.Management;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Vsk
 */
public class registerpanel extends javax.swing.JFrame {
   public static ArrayList<Management> managementList = new ArrayList<Management>();
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerpanel().setVisible(true);
                
            }
        });
    }
    /**
     * Creates new form panel
     */
    public registerpanel() {
        initComponents();
        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_np2 = new javax.swing.JTextField();
        txt_exam = new javax.swing.JTextField();
        txt_matter = new javax.swing.JTextField();
        txt_np1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        txt_sub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_clearinsert = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        error_matter = new javax.swing.JLabel();
        error_year = new javax.swing.JLabel();
        error_sub = new javax.swing.JLabel();
        error_np2 = new javax.swing.JLabel();
        error_np1 = new javax.swing.JLabel();
        error_exam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_query = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radio_repproved = new javax.swing.JRadioButton();
        radio_approved = new javax.swing.JRadioButton();
        btn_clearquery = new javax.swing.JButton();
        btn_listquery = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_query = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_clearreport = new javax.swing.JButton();
        btn_reportlist = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_report = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar");
        setResizable(false);

        txt_np2.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N

        txt_exam.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N

        txt_matter.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        txt_matter.setToolTipText("");
        txt_matter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_matterMousePressed(evt);
            }
        });

        txt_np1.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel1.setText("Ano");

        jLabel2.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel2.setText("NP2");

        jLabel3.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel3.setText("Matéria");

        jLabel4.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel4.setText("NP1");

        txt_year.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N

        txt_sub.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel5.setText("SUB");

        jLabel6.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel6.setText("EXAME");

        btn_clearinsert.setText("Limpar");
        btn_clearinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearinsertActionPerformed(evt);
            }
        });

        btn_insert.setText("Inserir");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btn_clearinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_matter, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txt_np1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(error_matter)
                            .addComponent(error_np1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_year)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(error_sub)
                                .addComponent(txt_year, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addComponent(txt_sub))
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_np2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(error_np2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_exam)
                            .addComponent(txt_exam, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_matter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error_matter)
                    .addComponent(error_year))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_np1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error_sub)
                    .addComponent(error_np1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_exam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_np2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error_np2)
                    .addComponent(error_exam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clearinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inserir", jPanel1);

        txt_query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_queryActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Fira Code Medium", 1, 14)); // NOI18N
        jLabel7.setText("Ano");

        radio_repproved.setText("Reprovadas");
        radio_repproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_repprovedActionPerformed(evt);
            }
        });

        radio_approved.setText("Aprovadas");
        radio_approved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_approvedActionPerformed(evt);
            }
        });

        btn_clearquery.setText("Limpar");
        btn_clearquery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearqueryActionPerformed(evt);
            }
        });

        btn_listquery.setText("Listar");
        btn_listquery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listqueryActionPerformed(evt);
            }
        });

        tbl_query.setAutoCreateRowSorter(true);
        tbl_query.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matéria", "Np1", "Np2", "Sub", "Exame", "Situação", "Ano"
            }
        ));
        tbl_query.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(tbl_query);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(txt_query)
                    .addComponent(radio_repproved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_approved, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btn_clearquery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_listquery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_query, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radio_approved)
                        .addGap(18, 18, 18)
                        .addComponent(radio_repproved)
                        .addGap(26, 26, 26)
                        .addComponent(btn_listquery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clearquery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel2);

        btn_clearreport.setText("Limpar");
        btn_clearreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearreportActionPerformed(evt);
            }
        });

        btn_reportlist.setText("Listar");
        btn_reportlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportlistActionPerformed(evt);
            }
        });

        tbl_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matéria", "Np1", "Np2", "Sub", "Exam", "Situação", "Ano"
            }
        ));
        jScrollPane3.setViewportView(tbl_report);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_reportlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_clearreport, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_reportlist, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clearreport, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Inserir");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btn_listqueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listqueryActionPerformed
        methods.show(tbl_query, managementList);
        for (int i = 0; i < tbl_query.getRowCount(); i++) {
            for (int j = 0; j < tbl_query.getColumnCount(); j++) {
                tbl_query.setValueAt("", i, j);
            }
        }
        for (int i=0; i < managementList.size(); i++) {
            if(radio_approved.isSelected() && managementList.get(i).returnStatus() == "Aprovado" || managementList.get(i).returnStatus() == "Aprovado por Exame"){
                if(txt_query.getText().length() > 0){
                    if(Integer.parseInt(managementList.get(i).returnYear()) == Integer.parseInt(txt_query.getText())){
                        list_matters(i);
                    }
                }else{
                    list_matters(i);
                }
            }else if(radio_repproved.isSelected() && managementList.get(i).returnStatus() == "Reprovado"){
                if(txt_query.getText().length() > 0){
                    if(Integer.parseInt(managementList.get(i).returnYear()) == Integer.parseInt(txt_query.getText())){
                        list_matters(i);
                    }
                }else{
                   list_matters(i);
                }
            }else if(txt_query.getText().length() > 0){
                if(Integer.parseInt(managementList.get(i).returnYear()) == Integer.parseInt(txt_query.getText())){
                    if(radio_approved.isSelected()){
                        if(managementList.get(i).returnStatus() == "Aprovado"){
                                list_matters(i);
                        }
                    }else if(radio_repproved.isSelected()){
                        if(managementList.get(i).returnStatus() == "Reprovado"){
                                list_matters(i);
                        }
                    }else{
                        list_matters(i);
                    }
                }
            }else if(!radio_approved.isSelected() && !radio_repproved.isSelected()){
                list_matters(i);
            }
        }
    }//GEN-LAST:event_btn_listqueryActionPerformed

    private void btn_clearqueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearqueryActionPerformed
        for (int i = 0; i < tbl_query.getRowCount(); i++) {
            for (int j = 0; j < tbl_query.getColumnCount(); j++) {
                tbl_query.setValueAt("", i, j);
            }
        }
    }//GEN-LAST:event_btn_clearqueryActionPerformed

    private void radio_approvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_approvedActionPerformed
        radio_repproved.setSelected(false);
    }//GEN-LAST:event_radio_approvedActionPerformed

    private void radio_repprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_repprovedActionPerformed
        radio_approved.setSelected(false);
    }//GEN-LAST:event_radio_repprovedActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        if(txt_matter.getText().length() == 0){error_matter.setText("Insira um nome para a matéria"); return;}
        if(txt_np1.getText().length() == 0 && Float.parseFloat(txt_np1.getText())>=0 && Float.parseFloat(txt_np1.getText())<=10){error_np1.setText("Valor inserido não aceito*");return;}
        if(txt_np2.getText().length() == 0 && Float.parseFloat(txt_np2.getText())>=0 && Float.parseFloat(txt_np2.getText())<=10){error_np2.setText("Valor inserido não aceito*");return;}
        if(txt_sub.getText().length() == 0 && Float.parseFloat(txt_sub.getText())>=0 && Float.parseFloat(txt_sub.getText())<=10){error_sub.setText("Valor inserido não aceito*");return;}
        if(txt_exam.getText().length() == 0 && Float.parseFloat(txt_exam.getText())>=0 && Float.parseFloat(txt_exam.getText())<=10){error_exam.setText("Valor inserido não aceito*");return;}
        if(txt_year.getText().length() == 0){error_year.setText("Valor inserido não aceito*");return;}
        //Management matterStudent = new Management(txt_matter.getText(),txt_year.getText(),txt_np1.getText(),txt_np2.getText(),txt_exam.getText(),txt_sub.getText());
        methods.Cadaster(txt_matter.getText(),txt_year.getText(),txt_np1.getText(),txt_np2.getText(),txt_exam.getText(),txt_sub.getText());
        
        //managementList.add(matterStudent);
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_clearinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearinsertActionPerformed
        txt_matter.setText("");
        txt_np1.setText("");
        txt_np2.setText("");
        txt_sub.setText("");
        txt_exam.setText("");
        txt_year.setText("");
    }//GEN-LAST:event_btn_clearinsertActionPerformed

    private void txt_matterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_matterMousePressed
        error_matter.setText("");
    }//GEN-LAST:event_txt_matterMousePressed

    private void btn_reportlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportlistActionPerformed
       
        methods.show(tbl_report, managementList);
        // TODO add your handling code here:
        for (int i = 0; i < tbl_report.getRowCount(); i++) {
            for (int j = 0; j < tbl_report.getColumnCount(); j++) {
                tbl_report.setValueAt("", i, j);
            }
        }
        for (int i=0; i < managementList.size(); i++) {
            tbl_report.setValueAt(managementList.get(i).returnMatter(), i, 0);
            tbl_report.setValueAt(managementList.get(i).returnNp1(), i, 1);
            tbl_report.setValueAt(managementList.get(i).returnNp2(), i, 2);
            tbl_report.setValueAt(managementList.get(i).returnSub(), i, 3);
            tbl_report.setValueAt(managementList.get(i).returnExam(), i, 4);
            tbl_report.setValueAt(managementList.get(i).returnStatus(), i, 5);
            tbl_report.setValueAt(managementList.get(i).returnYear(), i, 6);
        }
    }//GEN-LAST:event_btn_reportlistActionPerformed

    private void btn_clearreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearreportActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tbl_report.getRowCount(); i++) {
            for (int j = 0; j < tbl_report.getColumnCount(); j++) {
                tbl_report.setValueAt("", i, j);
            }
        }
    }//GEN-LAST:event_btn_clearreportActionPerformed

    private void txt_queryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_queryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_queryActionPerformed
   
    public void list_matters(int i){
        tbl_query.setValueAt(managementList.get(i).returnMatter(), i, 0);
        tbl_query.setValueAt(managementList.get(i).returnNp1(), i, 1);
        tbl_query.setValueAt(managementList.get(i).returnNp2(), i, 2);
        tbl_query.setValueAt(managementList.get(i).returnSub(), i, 3);
        tbl_query.setValueAt(managementList.get(i).returnExam(), i, 4);
        tbl_query.setValueAt(managementList.get(i).returnStatus(), i, 5);
        tbl_query.setValueAt(managementList.get(i).returnYear(), i, 6);
    }
    /**
     * @param args the command line arguments
     */

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clearinsert;
    private javax.swing.JButton btn_clearquery;
    private javax.swing.JButton btn_clearreport;
    public javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_listquery;
    private javax.swing.JButton btn_reportlist;
    private javax.swing.JLabel error_exam;
    private javax.swing.JLabel error_matter;
    private javax.swing.JLabel error_np1;
    private javax.swing.JLabel error_np2;
    private javax.swing.JLabel error_sub;
    private javax.swing.JLabel error_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radio_approved;
    private javax.swing.JRadioButton radio_repproved;
    public javax.swing.JTable tbl_query;
    private javax.swing.JTable tbl_report;
    private javax.swing.JTextField txt_exam;
    private javax.swing.JTextField txt_matter;
    private javax.swing.JTextField txt_np1;
    private javax.swing.JTextField txt_np2;
    private javax.swing.JTextField txt_query;
    private javax.swing.JTextField txt_sub;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
